extra_javascript: 
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
    - mdx_math

site_name: Costas
repo_url: https://github.com/csrg-utfsm/Costas
repo_name: 'GitHub'
site_description: 'Long period variable star study.'
site_author: 'wow'
copyright: 'so much copyright'

nav:
    - Home: index.md
    - Detection:
      - 'Data acquisition': 'datadq.md'
      - 'Preprocessing': 'preprocessing.md'
      - 'Features extraction': 'features.md'
      - 'General stars classification': 'starsclass.md'
    - Classification:
      - 'Cross-matching': 'crossmatching.md'
      - 'Dimensional reduction': 'dimred.md'
      - 'Clustering': 'clustering.md'
    - About: about.md